export let contributorsData = [
  {
    name: "Suraj Rai",
    gender: "male",
    role: "Maintainer",
    img: "https://avatars.githubusercontent.com/u/68278963?s=400&u=864e7632c62434a5e76b635f82fb23cc3b22dd31&v=4",
    twitter: "https://twitter.com/surajrai_z",
    github: "https://github.com/sr3688/",
    linkedin: "https://www.linkedin.com/in/sr3688/",
  },
  {
    name: "Surya Dana",
    gender: "male",
    role: "Contributor",
    img: "https://avatars.githubusercontent.com/u/69008196?s=88&u=bb00f3f72ca816505973cbec5b84f876bdb09dd5&v=4",
    twitter: "https://twitter.com/SuryaDa20408831",
    github: "https://github.com/surya-doc",
    linkedin: "https://www.linkedin.com/in/surya-dana-4787271b1/",
  },
  {
    name: "Thanasan Kumdee",
    gender: "male",
    role: "Contributor",
    img: "https://avatars.githubusercontent.com/u/28824919?v=4",
    twitter: "https://twitter.com/thnsn_kmd",
    github: "https://github.com/itzmeowww",
    linkedin: "https://www.linkedin.com/in/thanasan-kumdee",
  },
  {
    name: "Monesh Goyal",
    gender: "male",
    role: "Contributor",
    img: "",
    twitter: "https://twitter.com/GoyalMonesh",
    github: "https://github.com/2201monesh",
    linkedin: "https://www.linkedin.com/in/monesh-goyal-2b1325200/",
  },
  {
    name: "Ayan Gupta",
    gender: "male",
    role: "Contributor",
    img: "https://avatars.githubusercontent.com/u/71624964?s=400&u=cfa2be50e42d284228980a621f0b4ca3a78b3840&v=4",
    twitter: "https://twitter.com/ayangupta_9",
    github: "https://github.com/ayangupta9",
    linkedin: "https://www.linkedin.com/in/ayan-gupta-4b2158213/",
  },
  {
    name: "Pritam Kumar",
    gender: "male",
    role: "Contributor",
    img: "https://avatars.githubusercontent.com/u/84632214?v=4",
    twitter: "https://twitter.com/Pritamkr_",
    github: "https://github.com/pritam-kr",
    linkedin: "https://www.linkedin.com/in/pritam-kumar-0ab3431bb/",
  },
  {
    name: "Kavya Jain",
    gender: "Female",
    role: "Contributor",
    img: "https://avatars.githubusercontent.com/u/89743157?v=4",
    twitter: "",
    github: "https://github.com/ikavyajain",
    linkedin: "https://www.linkedin.com/in/kavya-jain-0365b11b4/",
  },

  {
    name: "Gaurav Pandey",
    gender: "male",
    role: "Contributor",
    img: "https://avatars.githubusercontent.com/u/51617083?s=400&u=3baf58ff4c82686f343018c33e38edc8fee290f1&v=4",
    twitter: "",
    github: "https://github.com/gaurav-Pandey09",
    linkedin: "https://www.linkedin.com/in/gaurav-pandey-75607b172",
  },
];
